### ISSUE TITLE
##[error]Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by thbl** [technote-space/auto-card-labeler#143]
I keep getting this error when workflow runs

```
Getting current labels...
  ##[error]Cannot convert undefined or null to object
  ##[error]Node run failed with exit code 1
```

**Comment by technote-space** [comment]
@thbl 
The project name written in `card-labeler.yml` may be different from the actual project name.
Please check your setting or project name.

**Comment by technote-space** [comment]
updated error message.

![201912170138](https://user-images.githubusercontent.com/39912269/70925106-07f1cd00-206e-11ea-9f83-168c1179883c.png)
