### ISSUE TITLE
[Question] Configuring the action setting for many projects

### ISSUE THREAD

**Issue by hussain5416** [technote-space/auto-card-labeler#230]
### Screenshot
![image](https://user-images.githubusercontent.com/78584556/109284450-e1205080-7845-11eb-9b2c-72077de9a789.png)

### Question
I've many projects in my private repo, I create and close projects **too often** How can I configure action setting for such case, Coz in settings *(above screenshot)*, I've to write down all the projects name, but **I don't want to modify the file each time I create a new project.**

**Comment by hussain5416** [comment]
@technote-space Need help. will you reply?

**Comment by technote-space** [comment]
If the program can be modified to allow you to specify the project name, etc. using regular expressions, etc., I think it will achieve the behavior you want.

I don't have any immediate plans to implement this behavior as I don't plan to use it myself.

You can fork or use this program as a reference to create your own actions.
