### ISSUE TITLE
Global Card support for all projects, in action settings

### ISSUE THREAD

**Issue by hussain5416** [technote-space/auto-card-labeler#238]
## Please describe your suggestion:
If there are many projects, or new projects are created and closed, then `action-settings.yml` have to be updated to work for that project, considering having many repositories, any many projects in those repos, It bocomes hassle to update `action-settings.yml` file every time you create a project in any repo.

## Describe the solution you'd like: 
Simply enable the global card, something like `*` in place of project name, to consider all the projects.
![image](https://user-images.githubusercontent.com/78584556/111056885-f2ee2e80-84a8-11eb-8084-14f8940f25ba.png)

## Describe alternatives you've considered:
There are no alternatives, User have to go through changing action settings every time a new project is created.

**Comment by technote-space** [comment]
You can use `SEARCH_PROJECT_BY_REGEXP` option

https://github.com/technote-space/auto-card-labeler/blob/master/action.yml#L16

```yaml

'.+':
   Column1:
   
   #...

```

**Comment by hussain5416** [comment]
@technote-space Not working, or maybe I'm doing something wrong
![image](https://user-images.githubusercontent.com/78584556/111105536-357f3c00-8579-11eb-8c52-7930e6fcba15.png)
![image](https://user-images.githubusercontent.com/78584556/111105561-48920c00-8579-11eb-8b69-89750f4344f4.png)

**Note:** In `card-labeler.yml` I tried `.+` both, with and without quotes.

**Comment by technote-space** [comment]
use v2
